@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace duke {
    namespace exceptions {
      class duke.exceptions.DukeException {
          + DukeException()
      }
    }
  }
  



right footer


PlantUML diagram
endfooter

@enduml
