@startuml

title __PARSER's Class Diagram__\n

  namespace duke {
    namespace parser {
      class duke.parser.Parser {
          {static} + KEYWORD_MULTIPLE_SPACE : String
          {static} + KEYWORD_ONE_SPACE : String
          {static} + createDeadline()
          {static} + createEvent()
          {static} + createTodo()
          {static} + findTaskDetail()
          {static} + getInputArray()
          {static} + parse()
          {static} - getElement()
      }
    }
  }
  



right footer


UML diagram
endfooter

@enduml
